In [10]:
import numpy as np



# ndarray: Nth dimensional array which is basically a numpy array.
# There are multiple reasons we use numpy array instead of python list some of them are:
# 1. More datatypes availabilty, 
# 2. Simple arithmatic operations can be performed easily between two ndarrays or within the ndarray itself with inbuilt numpy functions
# 3. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
# 4. Many logical operations can be performed on ndarray without using functions such as filter 
arr = np.array([[10, 20], [30, 40], [50, 60], [10, 20]])# This creates an ndarray using any iterable of python with .array() function of numpy
arr2 = np.array([[20, 30], [60, 90], [100, 50], [30, 10]])
# Performing mathematical operations on an NDArray returns their elements with the math operations performed.
# On the other hand if we perform addition on two python list it concatenates them.

# numpy has an extended list of data types that go beyond python's data types and it is an optional parameter when creating
# an ndarray if not specified it will automatically sense the datatype.
print("arr: \n", arr)
print(arr.dtype) # dtype - int32
print("arr2: \n", arr2)
print("Adding arr and arr2:")
print(arr+arr2)

s = b"Hello"

# .dtype() function is used to specify the datatype of the elements ndarray will have

dt = np.dtype([('age', np.int8)]) # We can also create a custom dtype for our ndarray
a = np.array([(10,), (20,), (30,)], dtype=dt)
print(a.dtype)# [('age', 'i1')]

print(type(a)) # Will return <class 'numpy.ndarray'>
print(np.array2string(a))

student=np.dtype([('name','S20'), ('age', 'i1'),('marks','f4')])
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype=student)
print(a)

arr: 
 [[10 20]
 [30 40]
 [50 60]
 [10 20]]
int32
arr2: 
 [[ 20  30]
 [ 60  90]
 [100  50]
 [ 30  10]]
Adding arr and arr2:
[[ 30  50]
 [ 90 130]
 [150 110]
 [ 40  30]]
[('age', 'i1')]
<class 'numpy.ndarray'>
[(10,) (20,) (30,)]
[(b'abc', 21, 50.) (b'xyz', 18, 75.)]
