In [12]:
import numpy as np

# .ones() and .zeros() are functions that behave the same and their task is to initialize arrays with a single value
# based on a shape passed in the first argument. the .ones() function fills the ndarray with 1s. and .zeros() fill it with
# 0s.

# Syntax: np.ones(shape, dtype= None, order= 'C')

a = np.ones((3,3), float, "C")

print(a)

print(a - 7)
print()
a = np.ones((1,2,3), str, "F")

print(a)
print()

a = np.zeros((4,5), [("Something", str),("Other Thing", int)], "C")

print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[-6. -6. -6.]
 [-6. -6. -6.]
 [-6. -6. -6.]]

[[['1' '1' '1']
  ['1' '1' '1']]]

[[('', 0) ('', 0) ('', 0) ('', 0) ('', 0)]
 [('', 0) ('', 0) ('', 0) ('', 0) ('', 0)]
 [('', 0) ('', 0) ('', 0) ('', 0) ('', 0)]
 [('', 0) ('', 0) ('', 0) ('', 0) ('', 0)]]
