In [6]:
import numpy as np

# Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

# NumPy provides a helper function: hstack() to stack along rows, vstack()  to stack along columns..

# Syntax is the same .h/vstack((arr1, arr2))

# Initalizing both arrays:
iter1 = [ x + 1 for x in range(1,11)]
a1 = np.array(iter1)
print("Array 1:\n",a1)
print()

iter2 = [ x * x for x in range(1,11)]
a2 = np.array(iter2)
print("Array 2:\n", a2)
print()

# hstack in action:
print("Stacking using hstack:")
print(np.hstack((a1,a2)))
print()

# Stacking using hstack:
# [  2   3   4   5   6   7   8   9  10  11   1   4   9  16  25  36  49  64
#   81 100]
# So, it just concatenates both arrays simple.


# vstack in action:
print("Stacking using vstack:")
print(np.vstack((a1,a2)))
print()

# Stacking using vstack:
# [[  2   3   4   5   6   7   8   9  10  11]
#  [  1   4   9  16  25  36  49  64  81 100]]
# So, it appends both the arrays in an empty array and creates a 2d array as a result.

Array 1:
 [ 2  3  4  5  6  7  8  9 10 11]

Array 2:
 [  1   4   9  16  25  36  49  64  81 100]

Stacking using hstack:
[  2   3   4   5   6   7   8   9  10  11   1   4   9  16  25  36  49  64
  81 100]

Stacking using vstack:
[[  2   3   4   5   6   7   8   9  10  11]
 [  1   4   9  16  25  36  49  64  81 100]]

