# Numpy Arrays:

In [22]:
import numpy as np

# Create a 1D array
arr1d = np.array([1, 2, 3, 4, 5])

# Create a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

# Create an array of zeros
zeros = np.zeros((3, 4))

# Create an array of ones
ones = np.ones((2, 5))

# Create an array with a range of values
range_arr = np.arange(0, 10, 2)
print(range_arr)
# Create an array with evenly spaced values
linspace_arr = np.linspace(0, 1, 5)

print(linspace_arr)
# Create a random array
rand_arr = np.random.rand(3, 4)

# Reshape an array
arr2d_reshaped = arr2d.reshape((3, 2))

# Transpose an array
arr2d_transposed = arr2d.T
print(arr2d_transposed)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[1 4]
 [2 5]
 [3 6]]


# Array Operations:

In [ ]:
# Indexing and slicing
arr = np.array([1, 2, 3, 4, 5])
arr[2] # 3
arr[1:3] # array([2, 3])

# Element-wise arithmetic operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a + b # array([5, 7, 9])
a - b # array([-3, -3, -3])
a * b # array([ 4, 10, 18])
a / b # array([0.25, 0.4 , 0.5 ])

# Broadcasting
a = np.array([1, 2, 3])
b = 2
a * b # array([2, 4, 6])

# Dot product
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# print(4*)
np.dot(a, b) # 32


# Array Functions:

In [30]:
# Sum, max, and min
arr = np.array([1, 2, 3, 4, 5])
np.sum(arr) # 15
np.max(arr) # 5
np.min(arr) # 1

# Mean Median and standard deviation
arr = np.array([1, 2, 3, 4, 5])
np.mean(arr) # 3.0
np.median(np.array([1, 2, 3, 4, 5])) # 3.0
np.std(arr) # 1.41421356

# Find the most frequent value or MODE:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

# Transcendental functions
arr = np.array([0, np.pi/2, np.pi])
np.sin(arr) # array([0.00000000e+00, 1.00000000e+00, 1.22464680e-16])
np.cos(arr) # array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])


TypeError: randint() got an unexpected keyword argument 'random_state'

# Array Manipulation:

In [40]:
# Concatenate arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate((a, b)) # array([1, 2, 3, 4, 5, 6])

# Stack arrays vertically
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.vstack((a, b)) # array([[1, 2, 3], [4, 5, 6]])

# Stack arrays horizontally
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.hstack((a, b)) # array([1, 2, 3, 4, 5, 6])

# Split arrays
arr = np.array([1, 2, 3, 4, 5, 6])
arr1, arr2 = np.split(arr, 2) # array([1, 2, 3]), array([4, 5, 6])


[1 2 3 4 5 6]


# Linear Algebra:

In [ ]:
# Matrix multiplication
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.dot(a, b) # array([[19, 22], [43, 50]])

# Matrix inversion
a = np.array([[1, 2], [3, 4]])
a_inv = np.linalg.inv(a) # array([[-2. ,  1. ], [ 1.5, -0.5]])

# Eigenvalues and eigenvectors
a = np.array([[1, 2], [3, 4]])
eig_vals, eig_vecs = np.linalg.eig(a)


# Other Functions:

In [49]:
# Boolean arrays
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3 # array([False, False, False,  True,  True])

# Indexing with boolean arrays
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3 # array([False, False, False,  True,  True])
arr[mask] # array([4, 5])

# Sorting
arr = np.array([3, 1, 4, 1, 5, 9, 2])
np.sort(arr) # array([1, 1, 2, 3, 4, 5, 9])


TypeError: only integer scalar arrays can be converted to a scalar index