In [170]:
import numpy as np
Z = np.random.randint(1,6,(6,3))
Z2 = np.random.randint(1,6,(6,3))

print(Z)
print(np.sum(Z))
print(Z*Z2)

[[1 5 1]
 [5 4 1]
 [1 5 5]
 [1 5 2]
 [1 4 1]
 [1 2 5]]
50
[[ 5 10  5]
 [20  4  2]
 [ 2 20 15]
 [ 1  5  6]
 [ 4 20  5]
 [ 1 10 15]]


In [202]:
# Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])


matrix = np.random.randint(1,5,(10,3))
# print(matrix)
# The hard way:
E = np.all(matrix[:,1:] == matrix[:,:-1], axis=1)
U = matrix[~E]
# print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = matrix[matrix.max(axis=1) != matrix.min(axis=1),:]
print(U)

# The easy way to find unique values 
print()
unique = np.unique(matrix, axis=1)
print(unique)
display(matrix)
print(np.diagonal(matrix))
square = np.random.randint(1,6,(4,4,4))
print(square)
print(np.diag(square))

[[4 1 3]
 [3 2 4]
 [4 1 1]
 [4 1 3]
 [3 2 1]
 [2 2 4]
 [3 2 4]
 [2 2 3]
 [3 1 1]]

[[1 3 4]
 [2 4 3]
 [1 1 4]
 [1 3 4]
 [2 1 3]
 [2 4 2]
 [2 4 3]
 [2 3 2]
 [1 1 1]
 [1 1 3]]


array([[4, 1, 3],
       [3, 2, 4],
       [4, 1, 1],
       [4, 1, 3],
       [3, 2, 1],
       [2, 2, 4],
       [3, 2, 4],
       [2, 2, 3],
       [1, 1, 1],
       [3, 1, 1]])

[4 2 1]
[[[3 5 5 5]
  [4 5 1 3]
  [4 3 1 3]
  [3 5 3 2]]

 [[1 4 1 2]
  [4 4 5 2]
  [5 5 4 3]
  [2 5 1 2]]

 [[3 3 5 5]
  [2 3 4 3]
  [4 4 2 1]
  [5 4 2 2]]

 [[5 3 5 5]
  [1 2 5 5]
  [1 5 5 5]
  [1 1 4 5]]]


ValueError: Input must be 1- or 2-d.

In [203]:
# Find the most frequent value:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

1
